version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: trainee20242  # MySQL
      MYSQL_DATABASE: mydb               # Banco
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: api_container
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:trainee20242@mysql:3306/mydb"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - minha_rede
    command: ["sh", "-c", "npx prisma migrate dev && npm run dev"]

volumes:
  mysql_data:

networks:
  minha_rede:
