version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: api_container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - app_network
    environment:
      DATABASE_URL: "mysql://root:trainee20242@mysql:3306/mydb"

  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: trainee20242
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
